var covidNepalisAbroad = {
  asOfDate: '2020-05-03',
  total: {
    infected: '2042',
    fatality: '49',
    recovered: '438',
  },
  countries: [
    {
      country: 'Australia',
      region: 'Oceania',
      infected: '11',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Bahrain',
      region: 'Middle East',
      infected: '49',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Belgium',
      region: 'Europe',
      infected: '6',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Canada',
      region: 'Americas',
      infected: '3',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Cyprus',
      region: 'Europe',
      infected: '3',
      fatality: '',
      recovered: '',
    },
    {
      country: 'France',
      region: 'Europe',
      infected: '1',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Germany',
      region: 'Europe',
      infected: '4',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Hong Kong',
      region: 'Asia',
      infected: '2',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Ireland',
      region: 'Europe',
      infected: '22',
      fatality: '1',
      recovered: '',
    },
    {
      country: 'Japan',
      region: 'Asia',
      infected: '2',
      fatality: '1',
      recovered: '1',
    },
    {
      country: 'Kuwait',
      region: 'Middle East',
      infected: '42',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Malaysia',
      region: 'Asia',
      infected: '3',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Malta',
      region: 'Europe',
      infected: '2',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Myanmar',
      region: 'Asia',
      infected: '1',
      fatality: '',
      recovered: '',
    },
    {
      country: 'Nepal',
      region: 'Asia',
      infected: '59',
      fatality: '',
      recovered: '16',
    },
    {
      country: 'New Zealand',
      region: 'Oceania',
      infected: '3',
      fatality: '',
      recovered: '2',
    },
    {
      country: 'Portugal',
      region: 'Europe',
      infected: '27',
      fatality: '',
      recovered: '3',
    },
    {
      country: 'Saudi Arabia',
      region: 'Middle East',
      infected: '4',
      fatality: '',
      recovered: '3',
    },
    {
      country: 'Spain',
      region: 'Europe',
      infected: '12',
      fatality: '',
      recovered: '10',
    },
    {
      country: 'Switzerland',
      region: 'Europe',
      infected: '5',
      fatality: '',
      recovered: '3',
    },
    {
      country: 'The Netherlands',
      region: 'Europe',
      infected: '',
      fatality: '1',
      recovered: '',
    },
    {
      country: 'Turkey',
      region: 'Europe',
      infected: '',
      fatality: '1',
      recovered: '',
    },
    {
      country: 'United Arab Emirates',
      region: 'Middle East',
      infected: '81',
      fatality: '2',
      recovered: '',
    },
    {
      country: 'United Kingdom',
      region: 'Europe',
      infected: '700',
      fatality: '33',
      recovered: '150',
    },
    {
      country: 'USA',
      region: 'Americas',
      infected: '1000',
      fatality: '10',
      recovered: '250',
    },
  ],
};
